### ISSUE TITLE
通过合约转token失败

### ISSUE THREAD

**Issue by zycChun** [frm430342210/ios-sdk-test#1]
我在通过ContractInvokeByAssetOperation 创建operation,然后调用合约转token。老是失败，我打印一下<Transaction 0x28154eb50>: {
    source_address: "RexxhrhbiXQzqSd3Ra19AEFkFa8Cq77wcibEBC3"
    nonce: 92
    fee_limit: 1000000
    gas_price: 1000
    metadata: "111"
    operations {
      type: PAY_ASSET
      source_address: "RexxhrhbiXQzqSd3Ra19AEFkFa8Cq77wcibEBC3"
      pay_asset {
        dest_address: "RexxhrhNg3M2ENSCGL7qrTwfBQtMedno9wQLRBm"
        asset {
          key {
            issuer: "RexxhrwM6C16ACPhUQnACNt3RZ8jHNp3PWLX3nf"
            code: "GCC"
          }
          amount: 100
        }
      }
    }
}
发现input参数没有传过去，请问要怎么改才能把input 传过去。

**Comment by frm430342210** [comment]
这个是我测试版本，可能存在问题，建议使用"https://github.com/bumoproject/bumo-sdk-ios"

**Comment by zycChun** [comment]
👌 谢谢

**Comment by frm430342210** [comment]
> 👌 谢谢

不客气
